### ISSUE TITLE
Improve testing of driver

### ISSUE THREAD

**Issue by rouault** [AbelPau/gdal#15]
### Feature description

@AbelPau In https://github.com/AbelPau/gdal/pull/12/commits/4d5cbe9bc5b8a5e65636daf751e69758d200e80a , I've added minimum testing of the writing side of the driver. You'll see there are 3 FIXME where I've disabled the checks of the content of the created files because they currently fail. The first one in test_ogr_miramon_write_simple_arc seems related to an issue with integer vs floating-point. The 2 other ones are about p[2] (the Z component) being changed during the creation process. I let you investigate and adjust.

There are no tests currently for the open options or layer creation options.
Open options are passed with ``gdal.OpenEx(filename, flag, open_options=["FOO=BAR", "BAR=BAZ"])``
Layer creations options are passed with ``ds.CreateLayer(name, options = ["FOO=BAR", "BAR=BAZ"])``

**Comment by AbelPau** [comment]
@rouault I've fixed "# FIXME: fails on assert f.GetField("LONG_ARC")" but there is something you have to know.
MiraMon have some Fields  that MUST be always there:
In the case of stringlines there are:
ID_GRAFIC: it's the FID of the feature.
N_VERTEXS: the number of the vertices of the stringline
LONG_ARC: the longitude of the arc.
NODE_INI: it's an identification of the node that is at the begining of the stringline. 
NODE_FI:  it's an identification of the node that is at the end of the stringline. 

The value of these fields are calculated when translating. They are the ones that driver calculate and they are like MUST BE.
After this mandatory fields are the fields of the layer. If a layer already have these fields (not usual because a normal layer have not these fields) their name is changed by another one with "2" or something like that behind (to avoid duplication). So, in the test, LONG_ARC becomes LONG_ARC2. The test should be with LONG_ARC2. 
Anyway, the test with LONG_ARC it should have worked and I've solved this error: LONG_ARC was calculated with 0 decimals and it should have had the same value than LONG_ARC (but only in this example). I changed the 0 deciamls to 6 decimals (usual precision in these calculation). And like the two values represent the same they are coincident.

Big long to explain. I hope you have understood. Perhaps in the doc file it should be explained (better than I have done now). Something like that:

For points:
If the layer have to translate to MiraMon format have some of the next fields they will be changed usually adding a "2" at the end of the field name:

ID_GRAFIC (that represents the internal FID of the stringline) -> ID_GRAFIC2
N_VERTEXS (that represents the number of the vertices of the stringline) -> N_VERTEXS2
LONG_ARC (that represents the longitude of the stringline) -> LONG_ARC2
NODE_INI (that represents the node that is at the begining of the stringline) -> NODE_INI2
NODE_FI (that represents the node that is at the end of the stringline) ->NODE_FI2

And the same for points (where this applyies only to ID_GRAFIC) and for polygons (where the names are diferent):
ID_GRAFIC (that represents the internal FID of the polygon) -> ID_GRAFIC2
N_VERTEXS (that represents the number of the vertices of the polygon) -> N_VERTEXS2
PERIMETRE (that represents the perimeter of the polygon) -> PERIMETRE2
AREA (that represents the area of the polygon) -> AREA2
N_ARCS (that represents the number of arcs of the polygon) -> N_ARCS2
N_POLIG (that represents the number of rings of the polygon) -> NODE_INI2

So, if you think it's necessary I can add something like that in documentation. If not, because a MiraMon used should know that, then, just be aware of that in the tests.

**Comment by AbelPau** [comment]
Z values solved. Indeed it was an error for me, cause it's all about the format and how it's read.
So, for me this Issue is closed except for the part comented above about the documentation.

**Comment by AbelPau** [comment]
writing using -lco Version=V2.0  added:

- test_ogr_miramon_write_simple_pointV20()
- test_ogr_miramon_write_simple_arcV20()
- test_ogr_miramon_write_simple_polygonV20()

**Comment by AbelPau** [comment]
writing using -lco CreationLanguage=CAT (SPA and ENG) added:
test_ogr_miramon_CreationLanguage()

**Comment by AbelPau** [comment]
writing using open_options=["OpenLanguage=" + Language]  added.
test_ogr_miramon_OpenLanguage()

But I find here a problem with grave letters.
autotest/ogr/ogr_miramon_vector.py::test_ogr_miramon_OpenLanguage[CAT] FAILED                                    [ 93%]
autotest/ogr/ogr_miramon_vector.py::test_ogr_miramon_OpenLanguage[SPA] FAILED                                    [ 96%]

The assert gives that: 
            if Language == "CAT":
>               assert field_description == "Identificador Gràfic intern"
E               AssertionError: assert 'Identificador GrÃ\xa0fic intern' == 'Identificador Gràfic intern'
E
E                 - Identificador Gràfic intern
E                 ?                 ^
E                 + Identificador GrÃ fic intern
E                 ?                 ^^

/gdal/build/autotest/ogr/ogr_miramon_vector.py:655: AssertionError

if Language == "SPA":
>                   assert field_description == "Identificador Gráfico interno"
E                   AssertionError: assert 'Identificador GrÃ¡fico interno' == 'Identificador Gráfico interno'
E
E                     - Identificador Gráfico interno
E                     ?                 ^
E                     + Identificador GrÃ¡fico interno
E                     ?                 ^^

So, when I read I recode to UTF-8 so, where the problem can be?
Even in QGis it seems good:
![image](https://github.com/AbelPau/gdal/assets/92721356/ed356b95-1941-4fa6-bf8c-209a174bdd94)

Perhaps it's only a matter of the windows cmd. But then the tests in actions would be good, but they are not.
So, it's better not to test that and rely on that the result is good?
I'll leave it as FIXME in the tests and I'll try the language from another file with no grave letters.

**Comment by rouault** [comment]
> So, if you think it's necessary I can add something like that in documentation

yes, that might be worth documenting there are "reserved" field names, and that there's logic that appends a '2' suffix to avoid collision between user field names with reserved ones.

**Comment by rouault** [comment]
> I'll leave it as FIXME in the tests and I'll try the language from another file with no grave letters.

I've re-enabled the checks disabled by those FIXME and CI seems happy with that. Where did you get the failures?

**Comment by AbelPau** [comment]
> > I'll leave it as FIXME in the tests and I'll try the language from another file with no grave letters.
> 
> I've re-enabled the checks disabled by those FIXME and CI seems happy with that. Where did you get the failures?

In a windows CMD line in a linux environment (using docker). Perhaps is only a matter of using it on windows. So, if it's ok, then, no worries.

**Comment by AbelPau** [comment]
> > So, if you think it's necessary I can add something like that in documentation
> 
> yes, that might be worth documenting there are "reserved" field names, and that there's logic that appends a '2' suffix to avoid collision between user field names with reserved ones.

Done!
